apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ⚠️
  labels:
    app.kubernetes.io/name: clair
    app.kubernetes.io/managed-by: clair-operator
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ⚠️
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
