apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: notifier-viewer-role
rules:
- apiGroups:
  - clair.projectquay.io
  resources:
  - notifiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clair.projectquay.io
  resources:
  - notifiers/status
  verbs:
  - get
