---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests.yaml
  - service.yaml

patchesStrategicMerge:
  - validatingwebhook_selector.yaml
  - mutatingwebhook_selector.yaml

configurations:
  - kustomizeconfig.yaml
