---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutate.clairproject.org
webhooks:
- name: v1alpha1.mutate.clairproject.org
  matchPolicy: Equivalent
  sideEffects: None
  failurePolicy: Fail
  admissionReviewVersions: [v1]
  rules:
  - operations: [CREATE]
    apiGroups: [clairproject.org]
    apiVersions: [v1alpha1]
    resources:
    - clairs
    - indexers
    - matchers
    - updaters
    - notifiers
    scope: Namespaced
  clientConfig:
    service:
      name: webhook-clairproject-org
      namespace: system
      path: /mutate/v1alpha1
