---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validate.projectclair.io
webhooks:
- name: v1alpha1.validate.projectclair.io
  matchPolicy: Equivalent
  sideEffects: None
  failurePolicy: Fail
  admissionReviewVersions: [v1]
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups: [projectclair.io]
    apiVersions: [v1alpha1]
    resources:
    - clairs
    - indexers
    - matchers
    - updaters
    - notifiers
    scope: Namespaced
  clientConfig:
    service:
      name: webhook-projectclair-io
      namespace: system
      path: /validate/v1alpha1
