---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: indexer-viewer-role
rules:
- apiGroups:
  - clairproject.org
  resources:
  - indexers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clairproject.org
  resources:
  - indexers/status
  verbs:
  - get
