---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - projectclair.io
  resources:
  - clairs
  - indexers
  - matchers
  - notifiers
  - updaters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - projectclair.io
  resources:
  - clairs/finalizers
  - indexers/finalizers
  - matchers/finalizers
  - notifiers/finalizers
  - updaters/finalizers
  verbs:
  - update
- apiGroups:
  - projectclair.io
  resources:
  - clairs/status
  - indexers/status
  - matchers/status
  - notifiers/status
  - updaters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmap
  - secret
  - service
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingress
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
