---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: updater-viewer-role
rules:
- apiGroups:
  - clairproject.org
  resources:
  - updater
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clairproject.org
  resources:
  - updater/status
  verbs:
  - get
