---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: clair
  app.kubernetes.io/managed-by: clair-operator

resources:
  - service.yaml
  - deployment.yaml
  - hpa.yaml
