---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - name: api
      port: 6060
      targetPort: api
  selector:
    app.kubernetes.io/name: clair
    app.kubernetes.io/managed-by: clair-operator
