---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clair-viewer-role
rules:
- apiGroups:
  - projectclair.io
  resources:
  - clairs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - projectclair.io
  resources:
  - clairs/status
  verbs:
  - get
