# permissions for end users to edit matchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: matcher-editor-role
rules:
- apiGroups:
  - clair.projectquay.io
  resources:
  - matchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clair.projectquay.io
  resources:
  - matchers/status
  verbs:
  - get
