---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: indexer-editor-role
rules:
- apiGroups:
  - projectclair.io
  resources:
  - notifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - projectclair.io
  resources:
  - notifiers/status
  verbs:
  - get
