---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clairs.clairproject.org.yaml
- indexers.clairproject.org.yaml
- matchers.clairproject.org.yaml
- notifiers.clairproject.org.yaml
# Updaters not ready for the operator yet.
#- updaters.clairproject.org.yaml
patches:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
  path: patches/cainjection.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
  path: patches/webhook_conversion.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
  path: patches/fixups_status_common.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: clairs.clairproject.org
  path: patches/fixups_clairs.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: (index|match|notifi)ers.clairproject.org
  path: patches/fixups_subresources.yaml
#- target:
#    group: apiextensions.k8s.io
#    version: v1
#    kind: CustomResourceDefinition
#    name: clairs.clairproject.org
#  path: patches/fixups_updaters.yaml
