---
apiVersion: projectclair.io/v1alpha1
kind: Clair
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/instance: test-sample
    app.kubernetes.io/part-of: clair
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: clair
  name: test-sample
spec:
  databases:
    indexer:
      name: databaseSecret
      key: database.json
    matcher:
      name: databaseSecret
      key: database.json
---
apiVersion: v1
kind: Secret
metadata:
  name: databaseSecret
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/instance: test-sample
    app.kubernetes.io/part-of: clair
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: clair
stringData:
  database.json: >
    {
      "indexer":{
        "connstring": "host=postgresql user=clair dbname=clair password=psqltest sslmode=disable"
      },
      "matcher":{
        "connstring": "host=postgresql user=clair dbname=clair password=psqltest sslmode=disable"
      }
    }
