---
apiVersion: projectclair.io/v1alpha1
kind: Notifier
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/instance: test-sample
    app.kubernetes.io/part-of: clair
    app.kubernetes.io/created-by: clair
  name: test-sample
spec:
  config:
    root:
      name: test-sample-config
      key: config.json
