---
apiVersion: clairproject.org/v1alpha1
kind: Clair
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/instance: test-sample
    app.kubernetes.io/part-of: clair
    app.kubernetes.io/created-by: clair
  name: test-sample
spec:
  databases:
    indexer:
      name: databaseSecret
      key: database.json
    matcher:
      name: databaseSecret
      key: database.json
