---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# All the resources in this directory should work, but these below are compiled
# to be streamlined into the example for the bundle.
resources:
- clair.yaml
- indexer.yaml
- matcher.yaml
- notifier.yaml
