---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: 'validate.projectclair.io'
webhooks:
- name: 'v1alpha1.validate.projectclair.io'
  matchPolicy: 'Equivalent'
  sideEffects: 'None'
  failurePolicy: 'Fail'
  rules:
  - operations: ['CREATE', 'UPDATE']
    apiGroups: ['projectclair.io']
    apiVersions: ['v1alpha1']
    resources:
    - 'clairs'
    - 'indexers'
    - 'matchers'
    - 'updaters'
    - 'notifiers'
    scope: 'Namespaced'
  clientConfig:
    service:
      name: 'webhook-projectquay-io'
      path: '/validate/v1alpha1'
      port: 8080
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: 'mutate.projectclair.io'
webhooks:
- name: 'v1alpha1.mutate.projectclair.io'
  matchPolicy: 'Equivalent'
  sideEffects: 'None'
  failurePolicy: 'Fail'
  rules:
  - operations: ['CREATE']
    apiGroups: ['projectclair.io']
    apiVersions: ['v1alpha1']
    resources:
    - 'clairs'
    - 'indexers'
    - 'matchers'
    - 'updaters'
    - 'notifiers'
    scope: 'Namespaced'
  clientConfig:
    service:
      name: 'webhook-projectquay-io'
      path: '/mutate/v1alpha1'
      port: 8080
