apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.3.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: clair-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: The Clair security scanner operator.
  displayName: Clair
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - clair
  - security
  links:
  - name: Clair Operator
    url: https://clair-operator.domain
  maintainers:
  - email: hdonnay@redhat.com
    name: Hank Donnay
  maturity: alpha
  provider:
    name: The Clair Authors
    url: https://quay.github.io/clair
  version: 0.0.1
