---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clairs.projectclair.io.yaml
- indexers.projectclair.io.yaml
- matchers.projectclair.io.yaml
- notifiers.projectclair.io.yaml
# Updaters not ready for the operator yet.
#- updaters.projectclair.io.yaml
patches:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
  path: patches/cainjection.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
  path: patches/webhook_conversion.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
  path: patches/fixups_status_common.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: clairs.projectclair.io
  path: patches/fixups_clairs.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: (index|match|notifi)ers.projectclair.io
  path: patches/fixups_subresources.yaml
#- target:
#    group: apiextensions.k8s.io
#    version: v1
#    kind: CustomResourceDefinition
#    name: clairs.projectclair.io
#  path: patches/fixups_updaters.yaml
