---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

#configMapGenerator:
#- files:
#  - controller_manager_config.yaml
#  name: manager-config

images:
- name: controller
  newName: quay.io/projectclair/clair-bundle
  newTag: 0.1.0
